[versions]
kotlin = "2.3.0"
th2-plugin = "0.3.14"
jmh = "1.37"

[libraries]
th2-codec = { group = "com.exactpro.th2", name = "codec", version = "5.6.3-dev" }

sailfish-common = { group = "com.exactpro.sf", name = "sailfish-common", version = "3.4.260" }
commons-beanutils = { group = 'commons-beanutils', name = 'commons-beanutils', version = '1.11.0' } # CVE-2025-48734 vulnerability in 1.9.4 version

kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version = "7.0.14" }

auto-service = { group = "com.google.auto.service", name = "auto-service", version = "1.1.1" }

jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh" }
jmh-generator-bytecode = { group = "org.openjdk.jmh", name = "jmh-generator-bytecode", version.ref = "jmh" }

junit-bom = { group = "org.junit", name = "junit-bom", version = "5.14.2" }
assertj-core = { group = "org.assertj", name = "assertj-core", version = "3.27.6" }

[plugins]
th2-component = { id = "com.exactpro.th2.gradle.component", version.ref = "th2-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jmh = { id = "me.champeau.jmh", version = "0.7.3" }